
const altalanosTudas = [
    { question: "Melyik bolygó a Naprendszer legnagyobb bolygója?", 
      options: ["Föld", "Neptunusz", "Jupiter", "Szaturnus"], 
      correctAnswer: "Jupiter" },
    { question: "Ki írta a 'Romeo és Júlia' című művet?",
      options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
      correctAnswer: "William Shakespeare" },
    { question: "Mi a víz kémiai képlete?",
      options: ["CO2", "H2O", "O2", "NaCl"],
      correctAnswer: "H2O" },
    { question: "Melyik országban található a Nagy Fal?",
      options: ["India", "Japán", "Kína", "Dél-Korea"],
      correctAnswer: "Kína" },
    { question: "Melyik a legrövidebb hónap?",
      options: ["Árilis", "November", "Február", "Szeptember"],
      correctAnswer: "Február" },
    { question: "Melyik kontinensen található a Szahara-sivatag?",
      options: ["Ázsia", "Afrika", "Ausztrália", "Észak-Amerika"],
      correctAnswer: "Afrika" },
    { question: "Milyen szín keletkezik, ha kéket és sárgát keverünk?",
      options: ["Zöld", "Narancssárga", "Lila", "Piros"], correctAnswer: "Zöld" },
    { question: "Melyik évben volt az első ember a Holdon?", 
      options: ["1969", "1975", "1959", "1980"],
      correctAnswer: "1969" },
    { question: "Hány lába van egy póknak?",
      options: ["6", "8", "10", "12"],
      correctAnswer: "8" },
    { question: "Mi Magyarország fővárosa?",
      options: ["Debrecen", "Győr", "Szeged", "Budapest"],
      correctAnswer: "Budapest" },
    { question: "Hány perc van egy órában?",
      options: ["60", "100", "30", "90"], 
      correctAnswer: "60" },
    { question: "Mi a fővárosa Olaszországnak?", 
      options: ["Madrid", "Róma", "Párizs", "Athén"], 
      correctAnswer: "Róma" },
    { question: "Hány évszak van egy évben?", 
      options: ["2", "3", "4", "5"], 
      correctAnswer: "4" },
    { question: "Mi a villámot kísérő hang?", 
      options: ["Szél", "Eső", "Mennydörgés", "Zivatar"], 
      correctAnswer: "Mennydörgés" },
    { question: "Mi a tojás héjának fő alkotóeleme?", 
      options: ["Kálcium", "Magnézium", "Vas", "Kén"], 
      correctAnswer: "Kálcium" },
    { question: "Milyen állat a Nemo?", 
      options: ["Bálna", "Delfin", "Bohóchal", "Polip"], 
      correctAnswer: "Bohóchal" },
    { question: "Mi a fővárosa Ausztriának?", 
      options: ["Bécs", "Berlin", "Prága", "Zürich"], 
      correctAnswer: "Bécs" },
    { question: "Hány csontból áll egy felnőtt ember váza?", 
      options: ["206", "189", "157", "254"], 
      correctAnswer: "206" },
    { question: "Milyen színű a smaragd?", 
      options: ["Piros", "Zöld", "Kék", "Sárga"], 
      correctAnswer: "Zöld" },
    { question: "Melyik sportban használják a 'touchdown' kifejezést?", 
      options: ["Rögbi", "Amerikai foci", "Kosárlabda", "Baseball"], 
      correctAnswer: "Amerikai foci" },
    { question: "Hány évig tartott az utolsó jégkorszak?", 
      options: ["5500", "25500", "11500", "1500"], 
      correctAnswer: "11500" },
    { question: "Mi az alap építőeleme a földi életnek?", 
      options: ["Oxigén", "Szén", "Hidrogén", "Nitrogén"], 
      correctAnswer: "Szén" },
    { question: "Mi a neve a világ leghosszabb kígyójának?", 
      options: ["Kobrák", "Pitón", "Anakonda", "Vipera"], 
      correctAnswer: "Pitón" },
    { question: "Melyik anyag nem vezeti az elektromosságot?", 
      options: ["Víz", "Réz", "Gumi", "Alumínium"], 
      correctAnswer: "Gumi" },
    { question: "Mi a leggyakoribb vércsoport?", 
      options: ["A", "B", "AB", "0"], 
      correctAnswer: "0" }
  ];

const tortenelem = [
    { question: "Mikor kezdődött az első világháború?",
      options: ["1912", "1914", "1918", "1920"],
      correctAnswer: "1914" },
    { question: "Ki volt az ókori Egyiptom legismertebb fáraója?",
      options: ["Ramszesz", "Tutankhamon", "Kleopátra", "Hatsepszut"],
      correctAnswer: "Tutankhamon" },
    { question: "Melyik ország fedezte fel Amerikát 1492-ben?",
      options: ["Anglia", "Spanyolország", "Portugália", "Franciaország"],
      correctAnswer: "Spanyolország" },
    { question: "Mikor omlott össze a Római Birodalom?",
      options: ["476", "1066", "1492", "732"],
      correctAnswer: "476" },
    { question: "Ki volt Magyarország első királya?",
      options: ["IV. Béla", "Szent István", "Károly Róbert", "Mátyás király"],
      correctAnswer: "Szent István" },
    { question: "Melyik városban épült a híres Akropolisz?",
      options: ["Athén", "Róma", "Spárta", "Karthágó"], 
      correctAnswer: "Athén" },
    { question: "Melyik évben omlott le a berlini fal?",
      options: ["1985", "1987", "1989", "1991"],
      correctAnswer: "1989" },
    { question: "Ki volt az USA első elnöke?",
      options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Theodore Roosevelt"],
      correctAnswer: "George Washington" },
    { question: "Mi volt a középkori járvány neve, amely milliókat ölt meg?",
      options: ["Vörös halál", "Spanyolnátha", "Fekete halál", "Kék himlő"],
      correctAnswer: "Fekete halál" },
    { question: "Melyik híres csatában vesztett Napóleon?",
      options: ["Waterloo", "Austerlitz", "Trafalgar", "Hastings"],
      correctAnswer: "Waterloo" },
    { question: "Melyik városban dobták le az első atombombát?", 
      options: ["Tokió", "Nagaszaki", "Hiroshima", "Osaka"], 
      correctAnswer: "Hiroshima" },
    { question: "Ki volt a Szovjetunió vezetője a második világháború alatt?", 
      options: ["Lenin", "Stálin", "Hruscsov", "Gorbacsov"], 
      correctAnswer: "Stálin" },
    { question: "Melyik éven tört ki a híres magyar forradalom Petőfi Sándor vezetésével?", 
      options: ["1939", "1956", "1848", "1867"], 
      correctAnswer: "1848" },
    { question: "Ki volt a híres macedón hódító?", 
      options: ["Nagy Sándor", "Cézár", "Hannibál", "Attila"], 
      correctAnswer: "Nagy Sándor" },
    { question: "Hány évig tartott a százéves háború?", 
      options: ["100", "112", "116", "80"], 
      correctAnswer: "116" },
    { question: "Ki volt a náci Németország vezetője?", 
      options: ["Mussolini", "Hitler", "Churchill", "Stalin"], 
      correctAnswer: "Hitler" },
    { question: "Mikor kezdődött a második világháború?", 
      options: ["1937", "1939", "1941", "1945"], 
      correctAnswer: "1939" },
    { question: "Melyik országban volt a Trianoni békeszerződés aláírása?", 
      options: ["Franciaország", "Spanyolország", "Anglia", "Németország"], 
      correctAnswer: "Franciaország" },
    { question: "Ki volt a francia forradalom idején a király?", 
      options: ["XIV. Lajos", "XVI. Lajos", "III. Napóleon", "I. Fülöp"], 
      correctAnswer: "XVI. Lajos" },
    { question: "Melyik nép építette a Machu Picchut?", 
      options: ["Maja", "Inka", "Azték", "Olmék"], 
      correctAnswer: "Inka" },
    { question: "Mikor volt a berlini fal építése?", 
      options: ["1949", "1955", "1961", "1972"], 
      correctAnswer: "1961" },
    { question: "Mi volt a neve a katonai szövetségnek, amelyben az USA és Nyugat-Európa együttműködött?", 
      options: ["NATO", "ENSZ", "Varsói Szerződés", "EU"], 
      correctAnswer: "NATO" },
    { question: "Hogyan halt meg Julius Caesar?", 
      options: ["Betegség", "Csatában", "Mérgezés", "Merénylet"], 
      correctAnswer: "Merénylet" },
    { question: "Mi volt az első civilizáció a Tigris és Eufrátesz mentén?", 
      options: ["Egyiptomi", "Maja", "Sumer", "Görög"], 
      correctAnswer: "Sumer" },
    { question: "Melyik világháborúban harcoltak lövészárkokban?", 
      options: ["Első", "Második", "Mindkettő", "Egyik sem"], 
      correctAnswer: "Első" }
];

const foldrajz = [
    { question: "Melyik a világ legnagyobb óceánja?",
      options: ["Atlanti-óceán", "Csendes-óceán", "Indiai-óceán", "Jeges-tenger"],
      correctAnswer: "Csendes-óceán" },
    { question: "Melyik ország fővárosa Tokió?",
      options: ["Kína", "Japán", "Thaiföld", "Dél-Korea"],
      correctAnswer: "Japán" },
    { question: "Hány kontinens van a Földön?",
      options: ["5", "6", "7", "8"],
      correctAnswer: "7" },
    { question: "Melyik folyó folyik keresztül Budapesten?",
      options: ["Tisza", "Duna", "Dráva", "Maros"],
      correctAnswer: "Duna" },
    { question: "Melyik hegységben található a Mont Blanc?",
      options: ["Kaukázus", "Alpok", "Andok", "Himalája"],
      correctAnswer: "Alpok" },
    { question: "Melyik országban van a Grand Canyon?",
      options: ["Kanada", "USA", "Mexikó", "Brazília"],
      correctAnswer: "USA" },
    { question: "Melyik ország zászlója piros-fehér-piros vízszintes csíkokból áll?",
      options: ["Ausztria", "Lengyelország", "Peru", "Dánia"],
      correctAnswer: "Ausztria" },
    { question: "Mi a világ legkisebb országa?",
      options: ["Monaco", "San Marino", "Vatikánváros", "Liechtenstein"],
      correctAnswer: "Vatikánváros" },
    { question: "Melyik ország fővárosa Canberra?",
      options: ["Ausztrália", "Új-Zéland", "Kanada", "Írország"],
      correctAnswer: "Ausztrália" },
    { question: "Melyik sivatag a legnagyobb a világon?",
      options: ["Gobi", "Kalahári", "Szahara", "Antarktisz"],
      correctAnswer: "Antarktisz" },
    { question: "Melyik ország fővárosa Bern?", 
      options: ["Svájc", "Ausztria", "Hollandia", "Norvégia"], 
      correctAnswer: "Svájc" },
    { question: "Melyik kontinensen található Argentína?", 
      options: ["Afrika", "Ázsia", "Dél-Amerika", "Európa"], 
      correctAnswer: "Dél-Amerika" },
    { question: "Mi a legmagasabb hegycsúcs a világon?", 
      options: ["Mont Blanc", "Kilimandzsáró", "Mount Everest", "Alpok"], 
      correctAnswer: "Mount Everest" },
    { question: "Melyik országban található az Eiffel-torony?", 
      options: ["Olaszország", "Spanyolország", "Franciaország", "Belgium"], 
      correctAnswer: "Franciaország" },
    { question: "Hány óceán van a Földön?", 
      options: ["3", "4", "5", "6"], 
      correctAnswer: "5" },
    { question: "Melyik város a legismertebb Velence után csatornáiról?", 
      options: ["Amszterdam", "Párizs", "London", "Róma"], 
      correctAnswer: "Amszterdam" },
    { question: "Melyik ország zászlaja kék-sárga?", 
      options: ["Svédország", "Ukrajna", "Hollandia", "Románia"], 
      correctAnswer: "Ukrajna" },
    { question: "Melyik város áll a Temze folyón?", 
      options: ["Liverpool", "Manchester", "London", "Oxford"], 
      correctAnswer: "London" },
    { question: "Mi az Amazonas fővárosa?", 
      options: ["Bogotá", "Manaus", "Lima", "Quito"], 
      correctAnswer: "Manaus" },
    { question: "Mi a fővárosa Norvégiának?", 
      options: ["Oslo", "Helsinki", "Koppenhága", "Stockholm"], 
      correctAnswer: "Oslo" },
    { question: "Melyik országban található a Taj Mahal?", 
      options: ["Pakisztán", "Nepál", "India", "Banglades"], 
      correctAnswer: "India" },
    { question: "Melyik országban van a Kilimandzsáró?", 
      options: ["Kenya", "Tanzánia", "Dél-Afrika", "Etiópia"], 
      correctAnswer: "Tanzánia" },
    { question: "Mi a neve Ausztrália bennszülött népének?", 
      options: ["Maorik", "Aboriginálok", "Zuluk", "Inuitok"], 
      correctAnswer: "Aboriginálok" },
    { question: "Melyik város híres a Colosseumról?", 
      options: ["Athén", "Isztambul", "Róma", "Madrid"], 
      correctAnswer: "Róma" },
    { question: "Melyik országban található a Machu Picchu?", 
      options: ["Peru", "Brazília", "Chile", "Argentína"], 
      correctAnswer: "Peru" }
    ];

const film = [
    { question: "Ki rendezte a 'Titanic' című filmet?", 
      options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Peter Jackson"],
      correctAnswer: "James Cameron" },
    { question: "Melyik színész játszotta Jack Sparrow kapitányt?", 
      options: ["Orlando Bloom", "Johnny Depp", "Leonardo DiCaprio", "Tom Hanks"], 
      correctAnswer: "Johnny Depp" },
    { question: "Melyik évben jelent meg az első Harry Potter-film?", 
      options: ["1999", "2001", "2003", "2005"], 
      correctAnswer: "2001" },
    { question: "Melyik film nyerte a legtöbb Oscar-díjat?", 
      options: ["Titanic", "Gyűrűk Ura: A király visszatér", "Ben-Hur", "Mindhárom"], 
      correctAnswer: "Mindhárom" },
    { question: "Ki alakította a Joker-t a 'The Dark Knight' című filmben?", 
      options: ["Joaquin Phoenix", "Jack Nicholson", "Heath Ledger", "Jared Leto"], 
      correctAnswer: "Heath Ledger" },
    { question: "Melyik filmben szerepel a Wakanda ország?", 
      options: ["Thor", "Fekete Párduc", "Doctor Strange", "Vasember"], 
      correctAnswer: "Fekete Párduc" },
    { question: "Melyik film főszereplője Optimus Fővezér?", 
      options: ["Star Wars", "Transformers", "Avatar", "Mission Impossible"],
      correctAnswer: "Transformers" }, 
    { question: "Melyik animációs filmben szerepel Olaf, a hóember?", 
      options: ["Coco", "Jégvarázs", "Shrek", "Toy Story"], 
      correctAnswer: "Jégvarázs" },
    { question: "Mi volt a Pixar első egész estés animációs filmje?", 
      options: ["Toy Story", "Némó nyomában", "Szörny Rt.", "Verdák"], 
      correctAnswer: "Toy Story" },
    { question: "Ki rendezte a 'Gyűrűk Ura' trilógiát?", 
      options: ["Peter Jackson", "Steven Spielberg", "James Cameron", "George Lucas"], 
      correctAnswer: "Peter Jackson" },
    { question: "Melyik Harry Potter ház jelképe a kígyó?", 
      options: ["Griffendél", "Hugrabug", "Mardekár", "Hollóhát"], 
      correctAnswer: "Mardekár" },
    { question: "Ki szinkronizálta Shreket az eredeti verzióban?", 
      options: ["Eddie Murphy", "Mike Myers", "Chris Rock", "Tom Hanks"], 
      correctAnswer: "Mike Myers" },
    { question: "Melyik film játszódik Pandora bolygóján?", 
      options: ["Star Wars", "Dűne", "Avatar", "Interstellar"], 
      correctAnswer: "Avatar" },
    { question: "Ki rendezte az 'Eredet' című filmet?", 
      options: ["Christopher Nolan", "Quentin Tarantino", "James Cameron", "Martin Scorsese"], 
      correctAnswer: "Christopher Nolan" },
    { question: "Melyik színésznő játszotta Hermionét?", 
      options: ["Emma Stone", "Emma Watson", "Natalie Portman", "Anne Hathaway"], 
      correctAnswer: "Emma Watson" },
    { question: "Melyik Disney hercegnő él a tenger alatt?", 
      options: ["Belle", "Ariel", "Hófehérke", "Csipkerózsika"], 
      correctAnswer: "Ariel" },
    { question: "Ki játssza James Bondot a 'Skyfall'-ban?", 
      options: ["Sean Connery", "Roger Moore", "Daniel Craig", "Pierce Brosnan"], 
      correctAnswer: "Daniel Craig" },
    { question: "Mi a neve Woody barátjának a Toy Storyban?", 
      options: ["Rex", "Buzz Lightyear", "Jessie", "Slink"], 
      correctAnswer: "Buzz Lightyear" },
    { question: "Melyik film zeneszerzője volt Hans Zimmer?", 
      options: ["Eredet", "Titanic", "Harry Potter", "Gladiátor"], 
      correctAnswer: "Eredet" },
    { question: "Melyik filmben szerepel a Delorean időgép?", 
      options: ["Star Wars", "Vissza a jövőbe", "Időhurok", "Tenet"], 
      correctAnswer: "Vissza a jövőbe" },
    { question: "Hány Oscar-díjat nyert a 'Titanic'?", 
      options: ["8", "9", "10", "11"], 
      correctAnswer: "11" },
    { question: "Ki rendezte a 'Ponyvargény' című filmet?",
      options: ["Quentin Tarantino", "Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg"], 
      correctAnswer: "Quentin Tarantino" },
    { question: "Ki alakította a főszerepet a 'Joker' című filmben?", 
      options: ["Joaquin Phoenix", "Heath Ledger", "Jared Leto", "Robert Pattinson"], 
      correctAnswer: "Joaquin Phoenix" },
    { question: "Ki rendezte a 'Schindler listája' című filmet?",
      options: ["Steven Spielberg", "Martin Scorsese", "Francis Ford Coppola", "James Cameron"], 
      correctAnswer: "Steven Spielberg" },
    { question: "Ki játszotta a főszerepet a 'Pókember' című filmben?",
      options: ["Tobey Maguire", "Andrew Garfield", "Tom Holland", "Chris Pratt"], 
      correctAnswer: "Tobey Maguire" }
  ];